### ISSUE TITLE
Unable to read long filenames when loading parameter files interactively

### ISSUE THREAD

**Issue by PaulTheLionHeart** [LegalizeAdulthood/iterated-dynamics#124]
![image](https://github.com/user-attachments/assets/049b2648-308e-456c-bc59-e3b8b62aceba)

It crashed in file: file_item.cpp:

![image](https://github.com/user-attachments/assets/0ff01984-70a8-4879-8a9f-ad9bdf96aa48)

filename = "C:\\Github\\id\\build-default\\win32\\fotd-master\\1997\\04\\1997.04.par"

**Comment by LegalizeAdulthood** [comment]
This is now fixed on master.  The issue wasn't long filenames per se, but some confusion about extensions when the base filename contained a `.` (dot).

**Comment by PaulTheLionHeart** [comment]
Very good. Well done Richard.

 

Is it easier to merge the fix with my version of ID or is the fix small enough to simply fix the code in my version?

 

Thanks 

 

Paul.

 

----------------------------------------------------------
Paul de Leeuw Computers     NSW Central Coast, Australia
Email:                             ***@***.*** ***@***.***> 
www:                           <https://deleeuw.com.au>
ABN                                         72 360 822 562
----------------------------------------------------------

**Comment by LegalizeAdulthood** [comment]
Hi Paul,

In article ***@***.***>,
    PaulTheLionHeart ***@***.***> writes:

> Is it easier to merge the fix with my version of ID or is the fix small
> enough to simply fix the code in my version?

Try the rebase first.  You'll need to learn how to do this in git
anyway :).  You won't lose any work as long as you commit any partial
changes to your branch first.

git rebase --abort

is your friend if you get conflicts.  Give it a try!

If you get conflicts, we can try a plan B.

-- Richard

-- 
"The Direct3D Graphics Pipeline" free book <http://tinyurl.com/d3d-pipeline>
            The Terminals Wiki <http://terminals-wiki.org>
     The Computer Graphics Museum <http://ComputerGraphicsMuseum.org>
  Legalize Adulthood! (my blog) <http://LegalizeAdulthood.wordpress.com>

**Comment by PaulTheLionHeart** [comment]
Okay Richard,

 

I’m brave 😊

 

Thanks

 

Paul.

 

----------------------------------------------------------
Paul de Leeuw Computers     NSW Central Coast, Australia
Email:                             ***@***.*** ***@***.***> 
www:                           <https://deleeuw.com.au>
ABN                                         72 360 822 562
----------------------------------------------------------
