### ISSUE TITLE
Manzpower fractal fails in bigflt

### ISSUE THREAD

**Issue by PaulTheLionHeart** [LegalizeAdulthood/iterated-dynamics#142]
Once bigflt is activated, the fractal only gives a screen with a single colour

**Comment by PaulTheLionHeart** [comment]
I've found a fault in bftoint() as it still uses 16 bit code. This function is only used in bailout routines. For ID 1.1 I will replace these routines with a slower and yet more accurate bigflt compare ratrher than using a long.

**Comment by LegalizeAdulthood** [comment]
Fixed
