### ISSUE TITLE
Dividebrot5 fractal fails in bigflt

### ISSUE THREAD

**Issue by PaulTheLionHeart** [LegalizeAdulthood/iterated-dynamics#143]
Once bigflt is activated, the fractal only gives a screen with a single colour

In fact, only Mandelbrot fractal successfully works in bignum mathematics.

**Comment by LegalizeAdulthood** [comment]
I suspect this is the same issue as with manzpower #142.  There is probably a bug in the switching of math types when precision of double is exceeded.

**Comment by LegalizeAdulthood** [comment]
We'll want an image compare test for the fractals that support deep zoom to verify that they all render correct compared to fractint when bignum math is used.

**Comment by PaulTheLionHeart** [comment]
I've found a fault in bftoint() as it still uses 16 bit code. This function is only used in bailout routines. For ID 1.1 I will replace these routines with a slower and yet more accurate bigflt compare ratrher than using a long.

**Comment by LegalizeAdulthood** [comment]
Fixed
