### ISSUE TITLE
Hot-link destinations not found in Document

### ISSUE THREAD

**Issue by PaulTheLionHeart** [LegalizeAdulthood/iterated-dynamics#159]
Additional fractals were added: Mandelbrot derivatives, Tierazon fractals and one Art Matrix fractal. Information on each fractal was added to helpp2.src and when a build is done, the following messages appear: The warnings are for the specific fractals added.

This is in the merged repository based on master downloaded 24/10/18 and merged with perturbation code being developed independently

13>[1328] Compiling: help.src
13>[0206] Making hot-links.
13>[0252] Paginating online help.
13>[0623] Paginating document.
13>[0549]    Warning help2.src 36: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 128: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 147: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 550: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 738: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 749: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 759: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 769: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 779: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 787: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 874: Hot-link destination is not in the document.
13>[0549]    Warning help2.src 930: Hot-link destination is not in the document.
13>[0716] Writing: helpdefs.h
13>[0719]    Note: Id must be re-compiled.
13>[0776] Writing: help_links.h
13>[0803] Writing: help_links.cpp
13>[1013] Writing: id.hlp
12>[0206] Making hot-links.
12>[0252] Paginating online help.

**Comment by LegalizeAdulthood** [comment]
This is the help compiler warning you that you defined a link target, but no link to the target was present elsewhere in the document.  Closing.
