### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by LegalizeAdulthood** [LegalizeAdulthood/iterated-dynamics#5]
The codeplex project had GPL v2, this one could have GPL v3.

**Comment by stuaxo** [comment]
Can this be GPLd?   Surely it is whatever "stone soup group" license they made, which predates the GPL?(Though, I haven't gone to check the original fractint to double check this)

**Comment by stuaxo** [comment]
I guess GPL should be possible, but it may need a notice, e.g. newer code is GPL, but older code is Freeware / SSG (whatever the docs actually say).

It's probably worth contacting the devs of Fractint, with any luck most of them will be contactable + up for relicensing to GPL, which would cover off the majority of it.

**Comment by LegalizeAdulthood** [comment]
They were contacted 10 yrs ago and never provided any useful information.
